### ISSUE TITLE
NOTE: Installing pip 10 compatibility fix

### ISSUE THREAD

**Issue by jhermann** [simion/pip-upgrader#10]
pip-upgrader imports internal modules of pip, and pip 10 changes things.

If you're used to self-apply pip-upgrader, this time it is:

**pip install -U pip-upgrader**

to get v1.4.6+. Just leaving this as a note to other people getting tangled up in dependency hell.

⇒ https://github.com/simion/pip-upgrader/commit/ba8613d47cd91f1e1f4ae546c561eb030ba5ddf8

**Comment by simion** [comment]
Yes, i'll have a look at this. Thanks for reporting

**Comment by simion** [comment]
the pip-location error was fixes :) also update the docs.
I personally keep pip-upgrader installed in my system, and use it for all my virtualenvs.
