### ISSUE TITLE
Choice prompt displaying incorrect characters on Windows 7

### ISSUE THREAD

**Issue by drepamig** [simion/pip-upgrader#17]
First off, this utility is very handy, thank you! 

I'm stuck on Windows 7 for a little while longer and noticed the "Choice:" prompt is displaying incorrect characters, as you can see below.

![image](https://user-images.githubusercontent.com/21010192/56365893-83397100-61b7-11e9-96db-184c0b15ae3a.png)

A little googling shows that a few other projects have had this issue (Git Bash, Babel) and it's related to ANSI color codes and incompatibility with Windows 7. Any chance you could disable the colors in Windows 7?

**Comment by simion** [comment]
Thanks for the report.
Will fix it in the next release. I'm planning some improivements, including `Pipfile` support :D

**Comment by simion** [comment]
Fixed & released
