### ISSUE TITLE
NameError: global name 'NoSectionError' is not defined  under Python 2.7

### ISSUE THREAD

**Issue by kierun** [simion/pip-upgrader#7]
I get this exception being raised when I call `pip-upgrade` with Python2.7. The problem is in `pip_upgrader/packages_status_detector.py", line 80`:

```
try:
    from configparser import ConfigParser, NoOptionError, NoSectionError
except ImportError:   # pragma: nocover
    from ConfigParser import ConfigParser, NoOptionError

[…]

except (NoOptionError, NoSectionError):  # pragma: nocover
```

If you have `ConfigParser` then the `NoSectionError` exception is not imported thus the above error.

**Comment by simion** [comment]
Hello,

Can you tell me what operating system you have?

**Comment by kierun** [comment]
This is on CentOS 7.

**Comment by kierun** [comment]
Changing 

`from ConfigParser import ConfigParser, NoOptionError`

to 

`from ConfigParser import ConfigParser, NoOptionError, NoSectionError`

fixed it for me.

**Comment by simion** [comment]
Done, released a new version of `pip-upgrader`, please install and check. Thanks

**Comment by kierun** [comment]
I can confirm this works fine.

Many thanks indeed, that was quick! ☺

**Comment by simion** [comment]
Cool, no problem 😄
